In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

data = pd.read_csv(r"urban_water_large_dataset.csv")
data.head()

,household_size,seasonal_index,garden_area,number_of_bathrooms,children_count,elderly_count,appliance_count,temperature,daily_liters_used
0,7.0,1.15,146.29,2.0,1.0,1.0,17.0,33.25,1316.830523
1,4.0,0.85,75.28,2.0,0.0,2.0,7.0,15.90,768.378303
2,5.0,1.50,239.47,1.0,2.0,1.0,16.0,31.70,1265.140365
3,7.0,1.14,10.21,2.0,3.0,2.0,10.0,21.01,1044.010486
4,3.0,1.46,158.99,4.0,3.0,2.0,17.0,30.56,1094.291599

In [2]:

# Handle missing values
data.fillna(data.mean(numeric_only=True), inplace=True)

,household_size,seasonal_index,garden_area,number_of_bathrooms,children_count,elderly_count,appliance_count,temperature,daily_liters_used
0,7.0,1.15000,146.29,2.0,1.0,1.0,17.0,33.25,1316.830523
1,4.0,0.85000,75.28,2.0,0.0,2.0,7.0,15.90,768.378303
2,5.0,1.50000,239.47,1.0,2.0,1.0,16.0,31.70,1265.140365
3,7.0,1.14000,10.21,2.0,3.0,2.0,10.0,21.01,1044.010486
4,3.0,1.46000,158.99,4.0,3.0,2.0,17.0,30.56,1094.291599
...,...,...,...,...,...,...,...,...,...
99995,4.0,1.00000,246.58,3.0,0.0,2.0,18.0,37.23,1026.322205
99996,1.0,1.22000,54.89,2.0,1.0,0.0,6.0,17.30,441.810618
99997,3.0,1.33000,128.41,2.0,3.0,1.0,14.0,26.45,889.794714
99998,2.0,1.14988,90.37,2.0,1.0,2.0,11.0,21.05,692.819655
99999,5.0,1.46000,201.08,2.0,0.0,1.0,17.0,31.45,1289.013911

In [3]:

# IQR Method for Outlier Removal
def remove_outliers(df):
    Q1 = df.quantile(0.25)
    Q3 = df.quantile(0.75)
    IQR = Q3 - Q1
    return df[~((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))).any(axis=1)]

data = remove_outliers(data)

In [4]:

# Features & Target
X = data.drop("daily_liters_used", axis=1)
y = data["daily_liters_used"]

In [5]:

# Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)