In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

data = pd.read_csv(r"urban_water_large_dataset.csv")
data.head()

,household_size,seasonal_index,garden_area,number_of_bathrooms,children_count,elderly_count,appliance_count,temperature,daily_liters_used
0,7.0,1.15,146.29,2.0,1.0,1.0,17.0,33.25,1316.830523
1,4.0,0.85,75.28,2.0,0.0,2.0,7.0,15.90,768.378303
2,5.0,1.50,239.47,1.0,2.0,1.0,16.0,31.70,1265.140365
3,7.0,1.14,10.21,2.0,3.0,2.0,10.0,21.01,1044.010486
4,3.0,1.46,158.99,4.0,3.0,2.0,17.0,30.56,1094.291599

In [2]:

# Handle missing values
data.fillna(data.mean(numeric_only=True), inplace=True)

,household_size,seasonal_index,garden_area,number_of_bathrooms,children_count,elderly_count,appliance_count,temperature,daily_liters_used
0,7.0,1.15,146.29,2.0,1.0,1.000000,17.0,33.25,1316.830523
1,4.0,0.85,75.28,2.0,0.0,2.000000,7.0,15.90,768.378303
2,5.0,1.50,239.47,1.0,2.0,1.000000,16.0,31.70,1265.140365
3,7.0,1.14,10.21,2.0,3.0,2.000000,10.0,21.01,1044.010486
4,3.0,1.46,158.99,4.0,3.0,2.000000,17.0,30.56,1094.291599
...,...,...,...,...,...,...,...,...,...
24995,1.0,1.08,165.42,1.0,2.0,2.000000,12.0,22.10,647.280813
24996,4.0,1.12,105.67,2.0,0.0,0.996124,8.0,43.93,898.703711
24997,7.0,1.30,223.48,3.0,1.0,1.000000,10.0,29.99,1426.711766
24998,6.0,0.94,20.26,1.0,0.0,1.000000,18.0,23.07,960.240962
24999,3.0,0.94,24.61,4.0,0.0,0.000000,5.0,24.46,727.228318